export const fallbackHomeContent = {
    siteConfig: {
        title: "Automivex | AI, Automation, SaaS & Shopify Software Company",
        description:
            "Automivex builds AI development, workflow automation, SaaS products, Shopify solutions, and computer vision systems with clear scope and fast delivery.",
        brand: "Automivex",
        websiteUrl: "https://www.automivex.com",
        contact: {
            primaryEmail: "hello@automivex.com",
        },
        legalLinks: [
            { href: "/privacy", label: "Privacy Policy" },
            { href: "/terms", label: "Terms & Conditions" },
            { href: "/cookies", label: "Cookie Policy" },
        ],
    },
    organizationStructuredData: {
        "@context": "https://schema.org",
        "@type": "Organization",
        name: "Automivex",
        url: "https://www.automivex.com",
        logo: "https://www.automivex.com/favicon.svg",
        email: "hello@automivex.com",
        description:
            "Automivex is a software development company specializing in AI development, automation engineering, computer vision, SaaS products, and Shopify engineering.",
        sameAs: [
            "https://www.linkedin.com/company/automivex/?viewAsMember=true",
            "https://www.freelancer.in/u/automivex",
        ],
        areaServed: "Worldwide",
        priceRange: "$$",
        serviceType: [
            "Software Development",
            "AI Development",
            "Automation Engineering",
            "Shopify Development",
            "SaaS Development",
        ],
        contactPoint: {
            "@type": "ContactPoint",
            contactType: "sales",
            email: "hello@automivex.com",
            url: "https://www.automivex.com/#book-call",
        },
    },
    hero: {
        eyebrow: "AI engineering for growth teams",
        title:
            "We build AI development, workflow automation, SaaS products, Shopify experiences, and computer vision systems.",
        description:
            "Automivex helps founders and operators ship practical software with clear scope, fast delivery, and measurable business impact.",
        primaryCta: { label: "Get a scoped plan", href: "#book-call" },
        secondaryCta: { label: "See services", href: "#services" },
        trustLine: "Fast response, clear scope, and practical delivery for ambitious teams.",
    },
    whyChoose: {
        eyebrow: "Why Automivex",
        title: "A tighter team, a clearer process, and software built for production",
        description:
            "We combine AI development, automation engineering, and practical product delivery so your team can move faster without unnecessary overhead.",
        points: [
            {
                title: "Focused delivery",
                description: "We narrow scope early so the build stays useful and predictable.",
            },
            {
                title: "Practical automation",
                description: "We turn repetitive work into efficient systems that are easier to manage.",
            },
            {
                title: "Clear ownership",
                description: "You get a direct partner for implementation, rollout, and follow-through.",
            },
        ],
    },
    proofSnapshot: {
        projectsDelivered: 55,
        workflowsAutomated: 140,
        clientSatisfaction: 98,
        averageResponseHours: 6,
        publishedAt: "2026-07-30",
    },
    services: [
        {
            key: "ai",
            iconKey: "ai",
            name: "AI Development",
            summary: "Practical AI features, integrations, and automation for high-value workflows.",
            bestFor: "Teams that want AI development that improves operations without disrupting delivery.",
            pain: "Manual work, scattered knowledge, and inconsistent decisions are slowing growth.",
            outcomes: "Faster execution, better insights, and more reliable process automation.",
            engagementModel: "Discovery-led implementation with phased rollout and measurable milestones.",
            timeline: "3 to 8 weeks",
            range: "3 to 8 weeks",
            basePrice: 8000,
            availability: "active",
            nextStep: "Book a discovery call to validate the right AI feature path.",
            deliverables: ["Workflow design", "AI implementation", "Launch support"],
            governance: {
                evidenceSummary: "Every engagement is reviewed for clarity, delivery risk, and outcome quality.",
                lastReviewedAt: "2026-07-30",
                reviewCycle: "monthly",
            },
        },
        {
            key: "automation",
            iconKey: "automation",
            name: "Workflow Automation",
            summary: "Automation engineering for approvals, reporting, handoffs, and internal operations.",
            bestFor: "Teams that need reliable automation engineering to reduce manual overhead.",
            pain: "Repetitive work is taking time away from higher-value work.",
            outcomes: "Fewer manual steps, more reliable handoffs, and faster operations.",
            engagementModel: "Focused process mapping and implementation sprint.",
            timeline: "2 to 6 weeks",
            range: "2 to 6 weeks",
            basePrice: 4000,
            availability: "active",
            nextStep: "Start with a short review of the workflow you want to streamline.",
            deliverables: ["Process mapping", "Automation build", "Support handoff"],
            governance: {
                evidenceSummary: "Workflow projects are scoped around impact, reliability, and change management.",
                lastReviewedAt: "2026-07-30",
                reviewCycle: "monthly",
            },
        },
        {
            key: "shopify",
            iconKey: "shopify",
            name: "Shopify Development",
            summary: "Shopify development support for storefront fixes, integration work, and conversion improvements.",
            bestFor: "Merchants who need practical Shopify development without agency bloat.",
            pain: "Storefront issues and slow improvements hurt conversion and team momentum.",
            outcomes: "Better storefront reliability, cleaner merchandising, and faster iteration.",
            engagementModel: "Short support sprint or scoped project delivery.",
            timeline: "1 to 4 weeks",
            range: "1 to 4 weeks",
            basePrice: 3000,
            availability: "active",
            nextStep: "Book a quick review to identify the best Shopify improvement path.",
            deliverables: ["Storefront fixes", "App work", "Ongoing support"],
            governance: {
                evidenceSummary: "Shopify work is prioritized around speed, stability, and business value.",
                lastReviewedAt: "2026-07-30",
                reviewCycle: "monthly",
            },
        },
        {
            key: "saas",
            iconKey: "saas",
            name: "SaaS Product Development",
            summary: "Full-stack SaaS product development for founders and product teams.",
            bestFor: "Teams building a SaaS product that needs a reliable technical foundation.",
            pain: "A strong MVP and architecture are needed quickly without overbuilding.",
            outcomes: "Faster launch readiness, better product stability, and clearer growth path.",
            engagementModel: "Product-focused discovery and implementation.",
            timeline: "4 to 12 weeks",
            range: "4 to 12 weeks",
            basePrice: 12000,
            availability: "limited",
            nextStep: "Share your product goals and we will suggest the best first milestone.",
            deliverables: ["Architecture", "MVP build", "Launch support"],
            governance: {
                evidenceSummary: "Product builds follow a practical roadmap and explicit delivery checkpoints.",
                lastReviewedAt: "2026-07-30",
                reviewCycle: "monthly",
            },
        },
        {
            key: "cv",
            iconKey: "cv",
            name: "Computer Vision",
            summary: "Computer vision and OCR workflows that reduce manual review and increase accuracy.",
            bestFor: "Teams handling image-heavy or document-heavy operations at scale.",
            pain: "Manual review is too slow, inconsistent, or expensive.",
            outcomes: "More automation, better consistency, and faster throughput.",
            engagementModel: "Data-aware implementation and deployment support.",
            timeline: "4 to 10 weeks",
            range: "4 to 10 weeks",
            basePrice: 10000,
            availability: "limited",
            nextStep: "Start with a short review of the workflow and the data you already have.",
            deliverables: ["Vision pipeline", "OCR workflow", "Testing plan"],
            governance: {
                evidenceSummary: "Computer vision work is designed around accuracy, reliability, and measurable ROI.",
                lastReviewedAt: "2026-07-30",
                reviewCycle: "monthly",
            },
        },
        {
            key: "quick-wins",
            iconKey: "quick-wins",
            name: "Quick Fixes & Support",
            summary: "Fast support for urgent bugs, fixes, and small integrations that need momentum quickly.",
            bestFor: "Teams facing blockers and needing a short delivery sprint.",
            pain: "A release blocker, small integration issue, or site fix is slowing delivery.",
            outcomes: "Quicker recovery, less disruption, and a clearer path forward.",
            engagementModel: "Short sprint with direct implementation support.",
            timeline: "2 to 10 days",
            range: "2 to 10 days",
            basePrice: 2500,
            availability: "active",
            nextStep: "Share the issue and we can outline the fastest solution path.",
            deliverables: ["Bug fixes", "Support sprint", "Follow-up QA"],
            governance: {
                evidenceSummary: "Low-friction support work is scoped around time, impact, and urgency.",
                lastReviewedAt: "2026-07-30",
                reviewCycle: "monthly",
            },
        },
    ],
    caseStudies: [
        {
            title: "AI workflow rollout",
            sector: "Operations",
            client: "Growth-stage team",
            summary: "Built an internal workflow that combined AI features, task routing, and clearer operations.",
            before: "The team relied on manual updates and fragmented handoffs.",
            after: "They now work from a more reliable, automated process with faster turnaround.",
            scope: ["Workflow analysis", "Automation build", "Operations support"],
            timeline: ["Discovery", "Implementation", "Rollout"],
            metrics: [
                { label: "Time saved", value: "12 hrs/week" },
                { label: "Faster handoffs", value: "2x" },
            ],
            evidence: ["Reduced manual steps", "Clearer process ownership", "More reliable delivery"],
            architecture: ["Discovery", "Implementation", "Launch"],
            governance: {
                evidenceSummary: "Case-study examples are reviewed for relevance and practical clarity.",
                lastReviewedAt: "2026-07-30",
                reviewCycle: "monthly",
            },
        },
    ],
    qualificationQuestions: [
        "What is the main problem you need solved first?",
        "What systems or tools are involved?",
        "What timeline or urgency is most important?",
        "What budget range feels realistic?",
        "Do you want a quick fix, a product build, or a longer rollout?",
    ],
    trustItems: [
        {
            id: "scope",
            title: "Scope stays grounded",
            summary: "We focus on the area with the highest business value first.",
            commitments: ["Clear milestones", "Practical scope", "Confidence around timing"],
            evidence: ["Small sprints", "Focused planning", "Direct communication"],
            governance: {
                evidenceSummary: "Scope is reviewed early so delivery stays practical and predictable.",
                lastReviewedAt: "2026-07-30",
                reviewCycle: "monthly",
            },
            iconKey: "sdlc",
        },
    ],
    projectTypeOptions: [
        "AI features",
        "Workflow automation",
        "Shopify improvements",
        "SaaS product build",
        "Computer vision workflow",
    ],
    budgetOptions: ["$2k-$5k", "$5k-$15k", "$15k+"],
};
